### ISSUE TITLE
Datepicker: styling of month/year picker incorrect depending on zoom-factor

### ISSUE THREAD

**Issue by robertspee-topicus** [vmware-clarity/ng-clarity#1751]
## Describe the bug

In clr/angular 17.7.0 and 17.7.1 the styling of month- en year-picker is incorrect. Months (or years) are listed in a single column that flows out of the pop-up. Depending on zoom-factor and display size/resolution they are correctly displayed in 2 columns or incorrectly in single too long columnn.

## How to reproduce

Can be reproduced on https://clarity.design/documentation/datepicker/code#examples 

1.  On Windows with Chrome, a display resolution of 1920x1080 and windows scale factor 100%  and chrome-zoom-factor of 90%. Can also be reproduced with other resolutions but with different chrome-zoom-factors.
2. Go to https://clarity.design/documentation/datepicker/code#examples
3.  Click on datepicker icon on basic-demo example (or any other datepicker on that page)
4.  Click on the current month in top left of pop-up
5. 12 months appear in a single coloums that flows out of the pop-up. See screenshot: ![Image](https://github.com/user-attachments/assets/ea780a25-4e12-49b6-bcd0-efa2169980d4)

## Expected behavior

All 12 months appear in 2 columns in the popup: see this screenshot with zoom-factor of 100% (or above) ![Image](https://github.com/user-attachments/assets/9be8a7b0-27ba-47a0-9226-33a0e2c6074b)

## Versions

**Clarity version:**
- [X] Other: v17.7.0 and v17.7.1

**Framework version:**
Angular 19.2.0

**Device:**

- Type: Laptop with external monitor
- OS: Windows 11
- Browser: Chrome
- Version 134.0.6998.89

## Additional notes

_Add any other notes about the problem here._

**Comment by venkateshr06** [comment]
Fixed and its available in v17.8.1

**Comment by mauritslourens** [comment]
it is still not fixed, see the Clarity website (and in our own project) when slightly zoomed out (90%):

![Image](https://github.com/user-attachments/assets/8eb1d511-09c7-4760-960d-d2dcd77ccc3a)

**Comment by venkateshr06** [comment]
Clarity website is yet to be synced with the latest fixes. Update the clarity version to 17.8.1 to see the fixes. Stackblitz for reference https://stackblitz.com/edit/61b91fr5-fbpaf8eg?file=src%2Fapp%2Fexample.component.ts

**Comment by valentin-mladenov** [comment]
@venkateshr06 is the website synced with the latest fixes?

Please, close the issue if so.
